<?php
/**
 * 動画サムネイル自動生成ヘルパー
 * SEO用サムネイル画像の自動生成と管理
 */

class VideoThumbnailHelper
{

    private $pdo;
    private $thumbnailDir;
    private $urlPrefix;

    public function __construct($pdo)
    {
        $this->pdo = $pdo;
        // テナントごとの画像ディレクトリ構成に合わせて調整が必要だが、
        // 一旦リファレンスに合わせて /img/video_thumbnails/ を使用
        // 将来的には /img/tenants/{tenant_id}/video_thumbnails/ 等が望ましい
        $this->thumbnailDir = $_SERVER['DOCUMENT_ROOT'] . '/img/video_thumbnails/';

        // プロトコルとホスト名を取得
        $protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off' || $_SERVER['SERVER_PORT'] == 443) ? "https://" : "http://";
        $host = $_SERVER['HTTP_HOST'];
        $this->urlPrefix = $protocol . $host;

        // サムネイルディレクトリが存在しない場合は作成
        if (!is_dir($this->thumbnailDir)) {
            if (!mkdir($this->thumbnailDir, 0755, true)) {
                error_log('Failed to create thumbnail directory: ' . $this->thumbnailDir);
            }
        }
    }

    /**
     * SEO用サムネイルURLを取得
     * 優先順位: 管理画面設定 > 自動生成 > デフォルト画像
     */
    public function getSeoThumbnailUrl($videoPath, $manualThumbnail = null, $castId = null, $videoType = null)
    {
        try {
            // 1. データベースに保存されたSEOサムネイルがある場合
            if ($castId && $videoType) {
                $dbSeoThumbnail = $this->getDbSeoThumbnail($castId, $videoType);
                if ($dbSeoThumbnail) {
                    return $this->normalizeUrl($dbSeoThumbnail);
                }
            }

            // 2. 管理画面で設定されたサムネイルがある場合（画像のみ）
            if (!empty($manualThumbnail) && $this->isImageFile($manualThumbnail)) {
                return $this->normalizeUrl($manualThumbnail);
            }

            // 3. 自動生成されたサムネイルがある場合
            $autoThumbnail = $this->getAutoGeneratedThumbnail($videoPath);
            if ($autoThumbnail) {
                return $autoThumbnail;
            }

            // 4. 動画から新しくサムネイルを生成
            $generatedThumbnail = $this->generateThumbnailFromVideo($videoPath, $castId, $videoType);
            if ($generatedThumbnail) {
                return $generatedThumbnail;
            }

            // 5. デフォルト画像 (ロゴなど)
            // ロゴパスが存在するか確認
            $logoPath = '/img/common/logo.png'; // プロジェクトに合わせて変更
            if (file_exists($_SERVER['DOCUMENT_ROOT'] . $logoPath)) {
                return $this->normalizeUrl($logoPath);
            }
            return ''; // ロゴもなければ空文字

        } catch (Exception $e) {
            error_log('VideoThumbnailHelper Error: ' . $e->getMessage());
            return '';
        }
    }

    /**
     * データベースからSEOサムネイルを取得
     */
    private function getDbSeoThumbnail($castId, $videoType)
    {
        try {
            // カラム名検証（SQLインジェクション対策）
            if (!in_array($videoType, ['movie_1', 'movie_2'])) {
                return null;
            }

            $column = "{$videoType}_seo_thumbnail";
            // tenant_casts テーブルを参照
            $stmt = $this->pdo->prepare("SELECT {$column} FROM tenant_casts WHERE id = ?");
            $stmt->execute([$castId]);
            $result = $stmt->fetch(PDO::FETCH_ASSOC);

            if ($result && !empty($result[$column])) {
                $path = $result[$column];
                // ファイルが存在するかチェック
                $fullPath = $_SERVER['DOCUMENT_ROOT'] . '/' . ltrim($path, '/');
                if (file_exists($fullPath)) {
                    return $path;
                }
            }

            return null;
        } catch (Exception $e) {
            error_log('getDbSeoThumbnail error: ' . $e->getMessage());
            return null;
        }
    }

    /**
     * ファイルが画像かどうかチェック
     */
    private function isImageFile($filePath)
    {
        $imageExtensions = ['jpg', 'jpeg', 'png', 'gif', 'webp', 'bmp'];
        $extension = strtolower(pathinfo($filePath, PATHINFO_EXTENSION));
        return in_array($extension, $imageExtensions);
    }

    /**
     * 既存の自動生成サムネイルを取得
     */
    private function getAutoGeneratedThumbnail($videoPath)
    {
        $videoName = pathinfo($videoPath, PATHINFO_FILENAME);
        $thumbnailPath = $this->thumbnailDir . $videoName . '_seo_thumb.jpg';

        if (file_exists($thumbnailPath)) {
            // ドキュメントルートからの相対パスに変換
            $relativePath = str_replace($_SERVER['DOCUMENT_ROOT'], '', $thumbnailPath);
            return $this->normalizeUrl($relativePath);
        }

        return null;
    }

    /**
     * 動画からサムネイル画像を生成
     */
    private function generateThumbnailFromVideo($videoPath, $castId = null, $videoType = null)
    {
        try {
            $fullVideoPath = $_SERVER['DOCUMENT_ROOT'] . '/' . ltrim($videoPath, '/');

            if (!file_exists($fullVideoPath)) {
                return null;
            }

            $videoName = pathinfo($videoPath, PATHINFO_FILENAME);
            $outputPath = $this->thumbnailDir . $videoName . '_seo_thumb.jpg';

            // FFmpegが利用可能な場合
            if ($this->isFFmpegAvailable()) {
                $result = $this->generateWithFFmpeg($fullVideoPath, $outputPath);
                if ($result) {
                    $relativePath = str_replace($_SERVER['DOCUMENT_ROOT'], '', $outputPath);
                    return $this->normalizeUrl($relativePath);
                }
            }

            // フォールバック: デフォルトサムネイル生成 (GD)
            $result = $this->generateDefaultThumbnail($outputPath, $castId);
            if ($result) {
                $relativePath = str_replace($_SERVER['DOCUMENT_ROOT'], '', $outputPath);
                return $this->normalizeUrl($relativePath);
            }

            return null;

        } catch (Exception $e) {
            error_log('Thumbnail generation error: ' . $e->getMessage());
            return null;
        }
    }

    /**
     * FFmpegでサムネイル生成
     */
    private function generateWithFFmpeg($videoPath, $outputPath, $timeSeconds = 3)
    {
        try {
            $ffmpegPath = $this->getFFmpegPath();
            if (!$ffmpegPath) {
                return false;
            }

            // 出力ディレクトリの書き込み権限チェック
            if (!is_writable(dirname($outputPath))) {
                error_log('Output directory is not writable: ' . dirname($outputPath));
                return false;
            }

            $command = sprintf(
                '%s -i %s -ss %d -vframes 1 -q:v 2 -vf "scale=1280:720:force_original_aspect_ratio=decrease,pad=1280:720:(ow-iw)/2:(oh-ih)/2" -y %s 2>/dev/null',
                escapeshellarg($ffmpegPath),
                escapeshellarg($videoPath),
                $timeSeconds,
                escapeshellarg($outputPath)
            );

            $returnCode = 0;
            $output = [];
            exec($command, $output, $returnCode);

            return ($returnCode === 0 && file_exists($outputPath));

        } catch (Exception $e) {
            error_log('FFmpeg generation error: ' . $e->getMessage());
            return false;
        }
    }

    /**
     * デフォルトサムネイル生成（GDライブラリ使用）
     */
    private function generateDefaultThumbnail($outputPath, $castId = null)
    {
        try {
            if (!extension_loaded('gd')) {
                return false;
            }

            $width = 1280;
            $height = 720;

            $image = imagecreatetruecolor($width, $height);

            // グラデーション背景
            for ($i = 0; $i < $height; $i++) {
                $ratio = $i / $height;
                $r = (1 - $ratio) * 245 + $ratio * 255;
                $g = (1 - $ratio) * 104 + $ratio * 210;
                $b = (1 - $ratio) * 223 + $ratio * 254;
                $color = imagecolorallocate($image, (int) $r, (int) $g, (int) $b);
                imageline($image, 0, $i, $width, $i, $color);
            }

            // ロゴ画像を重ねる（存在すれば）
            // TODO: テナントごとのロゴを取得するロジックが必要だが、一旦共通ロゴまたは無しで進める
            /*
            $logoPath = $_SERVER['DOCUMENT_ROOT'] . '/img/common/logo.png';
            if (file_exists($logoPath)) {
                $logo = imagecreatefrompng($logoPath);
                if ($logo) {
                    // ロゴの重ね合わせ処理（省略）
                    imagedestroy($logo);
                }
            }
            */

            // キャスト名追加（オプション）
            if ($castId) {
                $castName = $this->getCastName($castId);
                if ($castName) {
                    $textColor = imagecolorallocate($image, 255, 255, 255);
                    $shadowColor = imagecolorallocate($image, 0, 0, 0);
                    $text = $castName;

                    // フォント指定がないため、GD組み込みフォントを使用
                    // 日本語は文字化けするため、英数字のみあるいはフォントファイル指定が必要
                    // ここでは簡易的に処理

                    // 中央に配置
                    $fontSize = 5;
                    $textWidth = strlen($text) * imagefontwidth($fontSize); // マルチバイトだと幅がおかしくなるが許容
                    $x = ($width - $textWidth) / 2;
                    $y = ($height / 2);

                    imagestring($image, $fontSize, $x + 2, $y + 2, $text, $shadowColor);
                    imagestring($image, $fontSize, $x, $y, $text, $textColor);
                }
            }

            // JPEG形式で保存
            $result = imagejpeg($image, $outputPath, 85);
            imagedestroy($image);

            return $result;

        } catch (Exception $e) {
            error_log('Default thumbnail generation error: ' . $e->getMessage());
            return false;
        }
    }

    /**
     * FFmpegの利用可否チェック
     */
    private function isFFmpegAvailable()
    {
        return !empty($this->getFFmpegPath());
    }

    /**
     * FFmpegのパスを取得
     */
    private function getFFmpegPath()
    {
        $paths = ['/usr/bin/ffmpeg', '/usr/local/bin/ffmpeg', '/opt/homebrew/bin/ffmpeg', 'ffmpeg'];

        foreach ($paths as $path) {
            if (file_exists($path) && is_executable($path)) {
                return $path;
            }
            // whichコマンドでの確認
            $output = [];
            $returnVar = 0;
            exec("which $path 2>/dev/null", $output, $returnVar);
            if ($returnVar === 0 && !empty($output)) {
                return $output[0];
            }
        }

        return null;
    }

    /**
     * キャスト名を取得
     */
    private function getCastName($castId)
    {
        try {
            // tenant_casts テーブルを参照
            $stmt = $this->pdo->prepare("SELECT name FROM tenant_casts WHERE id = ?");
            $stmt->execute([$castId]);
            $result = $stmt->fetch(PDO::FETCH_ASSOC);
            return $result ? $result['name'] : null;
        } catch (Exception $e) {
            return null;
        }
    }

    /**
     * URLを正規化（ドメイン付与）
     */
    private function normalizeUrl($path)
    {
        if (strpos($path, 'http') === 0) {
            return $path;
        }

        $path = ltrim($path, '/');
        // 現在のドメインを使用
        return $this->urlPrefix . '/' . $path;
    }

    /**
     * 管理画面用：フレーム選択機能
     * 動画の複数フレームを生成して選択可能にする
     */
    public function generateFrameOptions($videoPath, $frameCount = 6)
    {
        try {
            $fullVideoPath = $_SERVER['DOCUMENT_ROOT'] . '/' . ltrim($videoPath, '/');

            if (!file_exists($fullVideoPath) || !$this->isFFmpegAvailable()) {
                return [];
            }

            $videoName = pathinfo($videoPath, PATHINFO_FILENAME);
            $frames = [];

            // 動画の長さを取得
            $duration = $this->getVideoDuration($fullVideoPath);
            if ($duration <= 0) {
                $duration = 30; // デフォルト30秒
            }

            // フレーム抽出間隔を計算
            $interval = max(1, floor($duration / $frameCount));

            for ($i = 0; $i < $frameCount; $i++) {
                $timeSeconds = $i * $interval;
                $framePath = $this->thumbnailDir . $videoName . "_frame_{$i}.jpg";

                if ($this->generateWithFFmpeg($fullVideoPath, $framePath, $timeSeconds)) {
                    $frames[] = [
                        'time' => $timeSeconds,
                        'path' => str_replace($_SERVER['DOCUMENT_ROOT'], '', $framePath),
                        'url' => $this->normalizeUrl(str_replace($_SERVER['DOCUMENT_ROOT'], '', $framePath))
                    ];
                }
            }

            return $frames;

        } catch (Exception $e) {
            error_log('Frame generation error: ' . $e->getMessage());
            return [];
        }
    }

    /**
     * 動画の長さを取得
     */
    private function getVideoDuration($videoPath)
    {
        try {
            $ffmpegPath = $this->getFFmpegPath();
            if (!$ffmpegPath)
                return 0;

            // ffprobeを探す（ffmpegと同じディレクトリにあると仮定）
            $ffprobePath = str_replace('ffmpeg', 'ffprobe', $ffmpegPath);
            if (!file_exists($ffprobePath) && !empty(shell_exec("which ffprobe 2>/dev/null"))) {
                $ffprobePath = trim(shell_exec("which ffprobe"));
            }

            if (!$ffprobePath)
                return 0;

            $command = sprintf(
                '%s -v quiet -show_entries format=duration -of csv="p=0" %s 2>/dev/null',
                escapeshellarg($ffprobePath),
                escapeshellarg($videoPath)
            );

            $duration = trim(shell_exec($command));
            return floatval($duration);

        } catch (Exception $e) {
            return 30; // デフォルト値
        }
    }

    /**
     * SEO用サムネイルをデータベースに保存
     * @param int $castId
     * @param string $videoType (movie_1, movie_2)
     * @param string $thumbnailPath 相対パス
     * @return bool
     */
    public function saveSeoThumbnail(int $castId, string $videoType, string $thumbnailPath): bool
    {
        if (!in_array($videoType, ['movie_1', 'movie_2'])) {
            error_log("Invalid videoType for saving SEO thumbnail: {$videoType}");
            return false;
        }

        $column = "{$videoType}_seo_thumbnail";

        try {
            // tenant_casts テーブルを更新
            $stmt = $this->pdo->prepare("UPDATE tenant_casts SET {$column} = :thumbnail_path, updated_at = NOW() WHERE id = :cast_id");
            $result = $stmt->execute([
                ':thumbnail_path' => $thumbnailPath,
                ':cast_id' => $castId
            ]);

            return $result && $stmt->rowCount() > 0;
        } catch (PDOException $e) {
            error_log("SEO thumbnail save error: " . $e->getMessage());
            return false;
        }
    }
}
